import { ClerkProvider } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { NavBar } from "./nav";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
    <ClerkProvider>
        <Head>
          <title>Who is Free</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="">
          <NavBar />
        </main>
    </ClerkProvider>
    </>
  );
}
